name: Build on archlinux

on:
  push:
    branches: [ "master", "zzxyb-branch-base"]
  pull_request:
    branches: [ "master", "zzxyb-branch-base"]

env:
  BUILD_TYPE: Release

jobs:
  meson-build:
    runs-on: ubuntu-latest
    container: archlinux:latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Install dependencies
      run: |
        pacman -Syu --noconfirm arch-install-scripts
        pacman-key --init
        pacman-key --populate archlinux

    - name: Update package databases
      run: pacman -Sy

    - name: Install dep
      run: |
        pacman -S --noconfirm base-devel meson pkgconfig cppcheck libx11 libxcb xcb-util-wm xcb-util xcb-util-keysyms xcb-util-errors cairo xcb-util-renderutil xcb-util-image xcb-util-cursor xcb-imdkit 

    - name: Build with Meson
      run: |
        meson builddir
        ninja -C builddir

    - name: Run cppcheck
      run: cppcheck --project=builddir/compile_commands.json
